_base_: '../_base_/cityscapes.yml'

batch_size: 24
iters: 120000



lr_scheduler:
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5
  learning_rate: 0.001


loss:
  types:
    - type: CrossEntropyLoss
    - type: DetailAggregateLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1,1,1,1]


optimizer:
  type: adam

model:
  type: CID1
  num_classes: 19
#  pretrained: ''

train_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.25
      max_scale_factor: 2.0
      scale_step_size: 0.05
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

val_dataset:
  type: Cityscapes
  dataset_root: datasets/cityscapes
  transforms:
    - type: Normalize
  mode: val

test_config:
  aug_eval: True
  scales: 1.0
